/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_autonavi_decode_H265ToJpeg */

#ifndef _Included_com_autonavi_decode_H265ToJpeg
#define _Included_com_autonavi_decode_H265ToJpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_autonavi_decode_H265ToJpeg
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_autonavi_decode_H265ToJpeg_decode
        (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
