/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_autonavi_socol_occtiltedserver_service_H265DecodeService */

#ifndef _Included_com_autonavi_socol_occtiltedserver_service_H265DecodeService
#define _Included_com_autonavi_socol_occtiltedserver_service_H265DecodeService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_autonavi_socol_occtiltedserver_service_H265DecodeService
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_autonavi_socol_occtiltedserver_service_H265DecodeService_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
